### PR TITLE
Use GNOME 47 runtime

### PR DESCRIPTION
**Pull request by A6GibKm**
Depends on: https://github.com/flathub/org.freedesktop.Sdk.Extension.typescript/pull/31

### CODE REVIEW

**Comment by A6GibKm** [comment]
bot, build

**Comment by A6GibKm** [comment]
cc @vixalien

**Comment by vixalien** [comment]
Nice. thanks!

**Comment by A6GibKm** [comment]
bump :eyes:

**Comment by vixalien** [comment]
oops. the link expired, and I can't test it anymore

**Comment by vixalien** [comment]
bot, build

**Comment by vixalien** [comment]
lgtm! thanks!!

**Pull request merged**
